# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCarrera', models.CharField(max_length=200, unique=True)),
                ('duracion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nivel3_app.Titulo')),
            ],
        ),
    ]
